[custom.all.ref1]
type   = "local"
path   = "."
ipkg   = "ref1.ipkg"

[custom.all.ref1-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.ref1-profile]
type   = "local"
path   = "profile"
ipkg   = "profile.ipkg"
